project_id = "qbhwlsyhnzihuqhnngna"

[auth]
enabled = true
site_url = "https://qbhwlsyhnzihuqhnngna.supabase.co"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.send-ong-registration]
verify_jwt = false