// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbhwlsyhnzihuqhnngna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiaHdsc3lobnppaHVxaG5uZ25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDg2NDEsImV4cCI6MjA3MjE4NDY0MX0.NPvvrxWZeIMa9Op5fXTXjMY5RJ4uk-7LpIFK0m05-Lk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});